# Generated by Django 2.2 on 2020-01-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog1post_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog1Post',
            new_name='BlogPost',
        ),
    ]
