# Generated by Django 2.2 on 2020-01-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200109_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slugs',
            field=models.SlugField(default='hello-world'),
            preserve_default=False,
        ),
    ]
