# Generated by Django 2.2 on 2020-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slugs',
            field=models.SlugField(null=True),
        ),
    ]
